### ISSUE TITLE
Empty string input in search not working right.

### ISSUE THREAD

**Issue by RaminMammadzada** [tadeuasarro/WeatherApp#2]
Not proper error message is shown when the search button is clicked with an empty string.
You can check the screenshot below. You can check the `error` object  by console log where your asynchronous program catches it. You may use `message` attribute of that object.
[](url)
![scrsht](https://user-images.githubusercontent.com/4702114/101176084-10fcf500-3657-11eb-98f4-804f0afb513b.png)

**Comment by tadeuasarro** [comment]
Probably try and use throw() to catch() the desired message.

**Comment by tadeuasarro** [comment]
.
